pinterest/config/routes.rb
Rails.application.routes.draw do
  resources :pins
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

pinterest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pinterest/app/models/pin.rb
class Pin < ApplicationRecord
  validates :photo, presence:true
  validates :description, presence:true
end

pinterest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

pinterest/app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

pinterest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

pinterest/app/helpers/application_helper.rb
module ApplicationHelper
end

pinterest/app/helpers/pins_helper.rb
module PinsHelper
end

pinterest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

pinterest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Pinterest</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>

</html>

pinterest/app/views/pins/_form.html.erb
<%= form_for(pin) do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, :class=> 'form-control' %>
      </div>
    </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :photo %><br>
      <%= f.text_field :photo, :class=> 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description, :class=> 'form-control' %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

pinterest/app/views/pins/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>Editing Pin</h1>
      <%= render 'form', pin: @pin %>
    </div>
  </div>
      <%= link_to 'Show', @pin %> |
      <%= link_to 'Back', pins_path %>
</div>

pinterest/app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Listing Pins</h1>
    <% @pins.each do |pin| %>
      <div class="col-md-3">
        <div class="thumbnail">
        <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img-responsive') %>
        <%= pin.description %>

        <div class="buttons" style="margin-top:10px; margin-bottom:10px">
          <%= link_to 'Show', pin, :class =>  'btn' %>
          <%= link_to 'Edit', edit_pin_path(pin), :class =>  'btn' %>
          <%= link_to 'Destroy', pin, :class =>  'btn', method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        </div>
      </div>
    <% end %>
<br>

<%= link_to 'New Pin', new_pin_path %>

</div>

pinterest/app/views/pins/new.html.erb
<div class="container">
    <h1>Create new pin</h1>
  <div class="row">
      <div class="col-md-6">
        <%= render 'form', pin: @pin %>
      </div>
  </div>
  <p><%= link_to 'Back', pins_path %> </p>
</div>

pinterest/app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pin.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style => 'width:500px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>

pinterest/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0px">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://www.google.com">Mi pinterest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Nosotros <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= pins_path %>">Pins</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

pinterest/app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
      <h1 class="titutos">Title</h1>
      <h2 class="titulos">Another title</h2>
      <a href="http://en1mes.com" class="btn btn-default ">
        <span class="glyphicon glyphicon-fire" style="color:orange"> </span>
        In1Month
      </a>
  </div>
</div>


<div class="container">
<div class="row">
  <div class="col-md-4">
    <div class="page-header">
      <h2 style="display:inline">Example page</h2>
      <span class="label label-default">New</span>
    </div>
      <p class="titulos"> Lorem ipsum dolor sit amet, consectetur
        adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut
        aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in
        voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur
        sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit
        anim id est laborum. </p>
  </div>

  <div class="col-md-4">
    <div class="page-header">
      <h2>Example page header</h2>
    </div>
      <p> Lorem ipsum dolor sit amet, consectetur
        adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua.
        Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut
        aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in
        voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur
        sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit
        anim id est laborum. </p>
  </div>

  <div class="col-md-4">
    <div class="page-header">
      <h2>Example page header</h2>
    </div>
    <p> Lorem ipsum dolor sit amet, consectetur
      adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut
      aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in
      voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur
      sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit
      anim id est laborum. </p>

    <h6>Sub ... subtitle</h6>
    <p> Lorem ipsum dolor sit amet, consectetur
      adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut
      aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in
      voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur
      sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit
      anim id est laborum. </p>

    <a href="http://en1mes.com">
      <img src="http://www.en1mes.com/assets/logo-79cc18afeb892865eb97c6b6641f7dc5.png"
           alt="logo de en 1 mes">
    </a>

    <hr>
    <br>

    <img src="http://s2.paultan.org/image/2016/05/Ford-Mustang-Shelby-Super-Snake-Australia-8-630x291.jpg" class="img-responsive">

    <ul>
      <li> Item1</li>
      <li> Item2</li>
      <li> Item3</li>
    </ul>

  </div>
</div>

</div>